### PR TITLE
Fix ShellCheck errors and warnings

### PR DESCRIPTION
**Pull request by CyberTailor**

### CODE REVIEW

**Comment by CyberTailor** [comment]
Guess I need to fix warnings too

**Comment by grobian** [comment]
these are not purely shellcheck errors/warnings, so it seems (|| return 1's appear to me behavioural)

I'm ok with some of the changes, but others seem like kind of nit-picking about style.  One important thing to mention is that bootstrap-prefix.sh isn't meant to be a POSIX shell script or anything, bootstrap-bash.sh exists for the sole purpose of obtaining a bash shell if none is available to run bootstrap-prefix.sh.  So things like declaration and assignment in one are perfectly fine, and there is no portability questions on those (since we always run with bash), AFAICT.

**Comment by CyberTailor** [comment]
Can you give a list of checks to deselect?

**Comment by grobian** [comment]
I don't know this tool, so no idea what checks I can pick from.

**Comment by pefoley2** [comment]
See also #19 which only resolves the error-level findings.
It's possible to tell shellcheck to only evaluate bash compliance, but that seems to be a global option:
https://github.com/ludeeus/action-shellcheck#shellcheck-options

We could probably have a separate action that checks only bootstrap-bash.sh for strict posix compliance and everything else only for bash-friendliness.

That said, there are a bunch of warnings even with -s bash:
shellcheck --format=gcc --shell=bash -S warning `find scripts -name '*.sh'`
https://termbin.com/d8egr

**Comment by CyberTailor** [comment]
oops, wrong branch

**Pull request closed without merging**
