### PR TITLE
sys-apps/portage: don't fail on start of stage3 on clang macos

### PR DESCRIPTION
**Pull request by DarthGandalf**
And drop old patch

### CODE REVIEW

**Comment by DarthGandalf** [comment]
@grobian

**Comment by grobian** [comment]
Why don't we just rm the 05prefix file from the portage inst in stage2?  If that works, it makes it all just a bit cleaner and focusses the hackwork on bootstrap-prefix.sh.

**Comment by thesamesam** [comment]
that sounds better to me too fwiw

**Comment by DarthGandalf** [comment]
Good idea. Will try that.

**Pull request closed without merging**
